---
title: "Calendar"
---

Upcoming events as of `r format(Sys.Date(), "%B, %Y")`:

```{r}
#| echo: false
#| message: false
#| warning: false

library(TeachingDemos)

```

::: {.panel-tabset}

### August

```{r}
#| echo: false
#| message: false
#| warning: false

setday <-cal(8,2026)                             ## August
setday(5)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(12)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(19)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(26)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")

```

### September

```{r}
#| echo: false
#| message: false
#| warning: false

setday <-cal(9,2026)                             ## September
setday(2)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(16)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(30)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")

```

### October

```{r}
#| echo: false
#| message: false
#| warning: false

setday <-cal(10,2026)                           
setday(7)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(14)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(21)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")
setday(28)
rect(-0.04,-0.04,1.04,1.04, col="#8aeaed")
text(0.5,0.5,"Practice \n 6:30")

```

:::
